export default [
  {
    id: 1,
    name: '1',
    description: 'this a test',
    picture: '/picture/hello',
    action: { move: 1 },
    ratio: 10,
  },
  {
    id: 2,
    name: '2',
    description: 'this a test',
    picture: '/picture/hello',
    action: { move: 2 },
    ratio: 10,
  },
  {
    id: 3,
    name: '3',
    description: 'this a test',
    picture: '/picture/hello',
    action: { move: 3 },
    ratio: 10,
  },
  {
    id: 4,
    name: '4',
    description: 'this a test',
    picture: '/picture/hello',
    action: { move: 4 },
    ratio: 10,
  },
  {
    id: 5,
    name: '5',
    description: 'this a test',
    picture: '/picture/hello',
    action: { move: 5 },
    ratio: 10,
  },
  {
    id: 5,
    name: 'Accident',
    description: 'this a test',
    picture: '/picture/hello',
    action: { stop: 'accident' },
    ratio: 3,
  },
  {
    id: 6,
    name: 'Panne d\'essence',
    description: 'this a test',
    picture: '/picture/hello',
    action: { stop: 'fuel' },
    ratio: 3,
  },
  {
    id: 7,
    name: 'Crevaison',
    description: 'this a test',
    picture: '/picture/hello',
    action: { stop: 'crevaison' },
    ratio: 3,
  },
  {
    id: 8,
    name: 'Limite de vitesse',
    description: 'this a test',
    picture: '/picture/hello',
    action: { slow: 2 },
    ratio: 4,
  },
  {
    id: 9,
    name: 'Feu rouge',
    description: 'this a test',
    picture: '/picture/hello',
    action: { stop: 'redLight' },
    ratio: 5,
  },
  {
    id: 10,
    name: 'Réparations',
    description: 'this a test',
    picture: '/picture/hello',
    action: { restart: 'accident' },
    ratio: 6,
  },
  {
    id: 11,
    name: 'Essence',
    description: 'this a test',
    picture: '/picture/hello',
    action: { restart: 'fuel' },
    ratio: 6,
  },
  {
    id: 12,
    name: 'Roue de secours',
    description: 'this a test',
    picture: '/picture/hello',
    action: { restart: 'crevaison' },
    ratio: 6,
  },
  {
    id: 13,
    name: 'Fin de limitation',
    description: 'this a test',
    picture: '/picture/hello',
    action: { slow: 5 },
    ratio: 6,
  },
  {
    id: 14,
    name: 'Feu vert',
    description: 'this a test',
    picture: '/picture/hello',
    action: { restart: 'redLight' },
    ratio: 14,
  },
  {
    id: 15,
    name: 'As du volant',
    description: 'this a test',
    picture: '/picture/hello',
    action: { bonus: 'as' },
    ratio: 1,
  },
  {
    id: 16,
    name: 'Camion citerne',
    description: 'this a test',
    picture: '/picture/hello',
    action: { bonus: 'citerne' },
    ratio: 1,
  },
  {
    id: 17,
    name: 'Increvable',
    description: 'this a test',
    picture: '/picture/hello',
    action: { bonus: 'increvable' },
    ratio: 1,
  },
  {
    id: 18,
    name: 'Prioritaire',
    description: 'this a test',
    picture: '/picture/hello',
    action: { bonus: 'prioritaire' },
    ratio: 1,
  },
];
